# Generated by Django 5.2 on 2025-08-27 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Work, Personal, Study)', max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for the category', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Task Category',
                'verbose_name_plural': 'Task Categories',
                'db_table': 'task_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True)),
                ('is_done', models.BooleanField(default=False, help_text='Whether the task is completed')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Task priority level', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, help_text='Optional deadline for the task', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Task category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_done'], name='tasks_user_id_b48c94_idx'), models.Index(fields=['user', 'category'], name='tasks_user_id_356301_idx'), models.Index(fields=['deadline'], name='tasks_deadlin_7f16a6_idx'), models.Index(fields=['created_at'], name='tasks_created_db4e37_idx')],
            },
        ),
    ]
