# Generated by Django 5.2.5 on 2025-09-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_chatsession_chatmessage'),
        ('tasks', '0002_taskcategory_owner_and_uniqueness'),
    ]

    operations = [
    ]
